### ISSUE TITLE
Could not load library pg_hint_plan (undefined symbol: RINFO_IS_PUSHED_DOWN)

### ISSUE THREAD

**Issue by fhouillo** [ossc-db/pg_hint_plan#22]
Hi,

On PG10 branch (commit 3cb8d0bf50e4ee23eb7c9c485d936cd3c4dce0a1), there's a warning at compile time:
```
core.c:1481:3: warning: implicit declaration of function 'RINFO_IS_PUSHED_DOWN' [-Wimplicit-function-declaration]
   if (only_pushed_down && !RINFO_IS_PUSHED_DOWN(rinfo, joinrel->relids))
   ^
```

It causes an error when pg_hint_plan is loaded:
```
postgres=# LOAD 'pg_hint_plan';
ERROR:  could not load library "/opt/intelerad/postgres10.3/lib64/pg_hint_plan.so": /opt/intelerad/postgres10.3/lib64/pg_hint_plan.so: undefined symbol: RINFO_IS_PUSHED_DOWN
```

It looks that the macro RINFO_IS_PUSHED_DOWN is used in core.c file but doesn't exist in pg10 .h files (only exists in pg11).
The bug has been introduced with the commit 375fdd256e264f8c32f9218c18c0f87b4c83bb8c.

Platform information:
OS Version : CENTOS 7
Posgresql version : 10.3
pg_hint_plan version : PG10 (3cb8d0bf50e4ee23eb7c9c485d936cd3c4dce0a1)

**Comment by LittleWuCoding** [comment]
I  also find that in PG10 there is no macro RINFO_IS_PUSHED_DOWN. Maybe we can fix by:
##1. As the pg10 source code, Many funtion in src/backend/optimizer/path/joinpath.c  replace macro 
```
INFO_IS_PUSHED_DOWN(rinfo, joinrel->relids)) 
```
with
```
rinfo->is_pushed_down
``` 
or 
##2. we replace the macro RINFO_IS_PUSHED_DOWN with it expansion in pg9.x or 11,
just replace 
```
INFO_IS_PUSHED_DOWN(rinfo, joinrel->relids)) 
```
with
```
((rinfo)->is_pushed_down ||  !bms_is_subset((rinfo)->required_relids, joinrelids))
``` 
Above are simple fix method,it can make pg_hint_palan works. Maybe  we can make further improvements.

**Comment by LittleWuCoding** [comment]
In the patch of PG10 [8b6294c7a560c115fb9027e9cc5a3eee17fdf419](https://github.com/postgres/postgres/commit/54eac6e8c5527c22555bc9f61ffa93cd0920b4c7#diff-07a18c2e8ef31c55604356df482f8cd4) , macro RINFO_IS_PUSHED_DOWN was reintroduced. So, pg_hint_plan will works well in latest release.Maybe we can add code to judge whehter the macro exists,if not exist, we create the macro ,otherwise,we use the postgres's macro

**Comment by fhouillo** [comment]
Thank you for your answer.
So the last version of PG_HINT_PLAN on PG10 branch is consistent with the [Postgres REL_10_STABLE branch](https://github.com/postgres/postgres/releases/tag//REL_10_STABLE) => I close the issue.
As I'm using postgres [10.3 version](https://github.com/postgres/postgres/releases/tag/REL_10_3), I will use this [PG_HINT_PLAN version](https://github.com/ossc-db/pg_hint_plan/commit/c56520a41063c0403afc6ec972b0eabffc19668c) that works with my Postgres version.
